sudo: false
language: node_js
node_js: stable
install:
  - npm install
services: mongodb
script:
  - npm run test
after_success:
  - npm run coverage
before_script:
  - sleep 15
  - mongo nisisiTest --eval 'db.createUser({user:"nisisiUser",pwd:"nisisi2020",roles:["readWrite"]});'
